D:\code\torch\base\Scripts\python.exe D:\code\torch\two\analyse\test_red16_score_date_statistic.py 
417
[('RedGap56', 378), ('RedGap45', 375), ('RedGap34', 365), ('RedGap23', 362), ('RedGap12', 358), ('Red1', 354), ('Red6', 354), ('Red2', 343), ('RedBlue', 340), ('Red3', 334), ('Red4', 329), ('RedGap25', 329), ('RedGap16', 327), ('RedSum25', 327), ('Red5', 326), ('RedSum16', 317), ('RedSum34', 314), ('RedSum_', 307)]
[('RedGap23', 60), ('Red4', 69), ('RedGap34', 69), ('RedSum_', 71), ('RedSum16', 71), ('Red2', 72), ('RedGap16', 73), ('RedGap25', 73), ('Red3', 74), ('RedSum25', 82), ('RedSum34', 82), ('Red6', 86), ('RedGap12', 87), ('Red1', 89), ('RedBlue', 89), ('RedGap56', 90), ('RedGap45', 95), ('Red5', 96)]

Process finished with exit code 0
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11
12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22
 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33